name: promosoluciones
description: App movil Promosoluciones para checadas con foto y GPS.
publish_to: "none"
version: 0.1.4+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  camera: any
  http: any
  geolocator: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/promosoluciones_icon.png
    - assets/promosoluciones_logo.png
